spring:
    application:
        name: test-task
    servlet:
        multipart:
            max-file-size: 500MB
            max-request-size: 1000MB
    mail:
        host: smtp.gmail.com
        port: 587
        username: zdraviymalish@gmail.com
        password: nfjz gwye cyxb yplw
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

amazonProperties:
    endpointUrl: https://storage.yandexcloud.net
    bucketName: hackathon-perm-cup-bucket

yandexApi:
    speechUri: https://transcribe.api.cloud.yandex.net
    operationUri: https://operation.api.cloud.yandex.net
    token: AQVNx1tbPR0KCm51us0xl5MpmqKEVf62k2lBCfpg
    speechEndpoint: /speech/stt/v2/longRunningRecognize
    statusEndpoint: /operations/{id}

email:
    enabled: "true"
    from: "zdraviymalish@gmail.com"
    username: "zdraviymalish@gmail.com"
    password: "nfjz gwye cyxb yplw"
    smtp:
        auth: "true"
        starttls:
            enable: "true"
        host: "smtp.gmail.com"
        port: "587"

scheduler:
    updateTextFixedRate: 10000

jwt:
    token:
        access:
            expiration: 900000
            secret: 13A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
        refresh:
            expiration: 86400000
            secret: 33A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327851
