spring:
    application:
        name: test-task

logging:
    level:
        org.springframework.security: trace
        redis.clients.jedis.exceptions: trace
jwt:
    token:
        access:
            expiration: 900000
            secret: 13A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
        refresh:
            expiration: 86400000
            secret: 33A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327851