spring:
  liquibase:
    enabled: false

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jooq:
    sql-dialect: postgres

  data:
    redis:
      port: ${SPRING_REDIS_PORT}
      host: ${SPRING_REDIS_HOST}

server:
  port: 8080