---
apiVersion: v1
kind: Service
metadata:
  name: api-application
  labels:
    app: api-application
spec:
  ports:
    - port: 8080
      targetPort: application
      protocol: TCP
      name: http
  selector:
    app: api-application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-application
  labels:
    app: api-application
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: api-application
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-application
    spec:
      initContainers:
        - name: liquibase
          image: test-db:latest
          imagePullPolicy: "IfNotPresent"
          args:
            - update
          env:
            - name: DB_URL
              value: jdbc:postgresql://postgres:5432/Hackathon
            - name: DB_SCHEMA
              value: public
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: vsemky
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - api-application
              topologyKey: kubernetes.io/hostname
      containers:
        - name: api-application
          image: academy-grafana-test-api:latest
          imagePullPolicy: "IfNotPresent"
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/Hackathon
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: vsemky
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
          ports:
            - name: application
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: application
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 15
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path:  /actuator/health
              port: application
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 2
            failureThreshold: 10
          resources:
            limits:
              cpu: 800m
              memory: 800Mi
            requests:
              cpu: 400m
              memory: 600Mi